language: go

go: 1.4

install:
  - go get github.com/fzipp/gocyclo
  - go get github.com/golang/lint
  - go get golang.org/x/tools/cmd/vet
  - go get github.com/tools/godep
  - go get gopkg.in/mgo.v2

services:
  - mongodb

script: godep go test -cover ./...
